---

- name: backup router configuration with cli_command module
  hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:
    - name: backup config
      cli_command:
        command: show run
      register: backup

    - name: move to file
      copy:
        content: "{{ backup.stdout }}"
        dest: "lab2/backup/{{ inventory_hostname }}_config.{{ lookup('pipe','date +%Y-%m-%d@%H:%M') }}"
        
    - name: REMOVE NON CONFIG LINES
      lineinfile:
        path: "lab2/backup/{{ inventory_hostname }}_config.{{ lookup('pipe','date +%Y-%m-%d@%H:%M') }}"
        line: "Building configuration..."
        state: absent

    - name: REMOVE NON CONFIG LINES - REGEXP
      lineinfile:
        path: "lab2/backup/{{ inventory_hostname }}_config.{{ lookup('pipe','date +%Y-%m-%d@%H:%M') }}"
        regexp: 'Current configuration.*'
        state: absent
