--- 
- name: Configure GRE Tunnel
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
  - name: create tunnel interface to R0
    ios_config:
      lines:
       - 'ip address 172.16.<<studentID>>.10 255.255.255.0'
       - 'tunnel source GigabitEthernet2'
       - 'tunnel destination 10.2.0.10'
       - 'description Tunnel to R0'
      parents: interface Tunnel 0
